name: PHP CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

  steps:
      - uses: actions/checkout@v2

      - name: Setup project
        run: make setup

      - name: Execute tests
        run: make test